### ISSUE TITLE
Multiple classes cannot be fine-tuned and tested?

### ISSUE THREAD

**Issue by Caltech-Z** [ZhangGongjie/Meta-DETR#57]
Traceback (most recent call last):
  File "/home/zzjy/anaconda3/envs/meta_detr/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zzjy/anaconda3/envs/meta_detr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zzjy/anaconda3/envs/meta_detr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zzjy/Code/Meta-DETR/datasets/dataset_support.py", line 73, in __getitem__
    i = index % self.classlendict[classid]
ZeroDivisionError: integer division or modulo by zero

**Comment by ZhaoPo** [comment]
> 回溯（最近一次调用）：文件 “/home/zzjy/anaconda3/envs/meta_detr/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py”，第 302 行，在 _worker_loop data = fetcher.fetch（index） 文件 “/home/zzjy/anaconda3/envs/meta_detr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py”，第 58 行，在 fetch data = [self.dataset[idx] for idx in possibly_batched_index]文件 “/home/zzjy/anaconda3/envs/meta_detr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py”，第 58 行，在 data = [self.dataset[idx] for idx in possibly_batched_index] 文件 “/home/zzjy/Code/Meta-DETR/datasets/dataset_support.py”，第 73 行，在 **getitem** i = index % self.classlendict[classid] ZeroDivisionError：整数除法或取模被零

**Comment by ZhaoPo** [comment]
Hello, I also encountered the same problem when I was fine-tuning, may I ask if you have solved it? Is it convenient for me to exchange guidance? Looking forward to your reply.
