### ISSUE TITLE
cannot import name '_NewEmptyTensorOp' from 'torchvision.ops.misc'

### ISSUE THREAD

**Issue by syluofoden** [ZhangGongjie/Meta-DETR#85]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import datasets
  File "/home/lsy/Meta-DETR-main/datasets/__init__.py", line 6, in <module>
    from .dataset import build
  File "/home/lsy/Meta-DETR-main/datasets/dataset.py", line 10, in <module>
    from util.misc import get_local_rank, get_local_size
  File "/home/lsy/Meta-DETR-main/util/misc.py", line 24, in <module>
    from torchvision.ops.misc import _NewEmptyTensorOp
ImportError: cannot import name '_NewEmptyTensorOp' from 'torchvision.ops.misc' (/home/lyk/anaconda3/envs/mdetr/lib/python3.8/site-packages/torchvision/ops/misc.py)
I encountered the above issue during runtime. My versions of torch and torchvision are as follows.
pytorch == 1.10.q+cu111
torchvision == 0.11.2+cu111
Could you please advise how to resolve this?

**Comment by ningsummerw** [comment]
请问你解决这个问题了吗，我也遇到了这个同样的问题

**Comment by syluofoden** [comment]
换其他的torch版本，需要和python以及你用的cuda驱动版本相对应，原作者和readme里面给的torch版本有点低了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月06日 19:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ZhangGongjie/Meta-DETR] cannot import name '_NewEmptyTensorOp' from 'torchvision.ops.misc' (Issue #85) |

请问你解决这个问题了吗，我也遇到了这个同样的问题

**Comment by ningsummerw** [comment]
好的，谢谢，请问你复现出这个代码吗，有些问题能向你咨询吗，非常感谢

**Comment by syluofoden** [comment]
复现出来了，有什么问题你问吧，我尽量回答









在 2024-12-08 10:54:24，"ningsummerw" ***@***.***> 写道：

好的，谢谢，请问你复现出这个代码吗，有些问题能向你咨询吗，非常感谢

**Comment by syluofoden** [comment]
如果想的话你可以加一下我vx：syluofoden47 这样子稍微方便一些









在 2024-12-08 10:54:24，"ningsummerw" ***@***.***> 写道：

好的，谢谢，请问你复现出这个代码吗，有些问题能向你咨询吗，非常感谢

**Comment by KarmaQI** [comment]
> Traceback (most recent call last): File "main.py", line 13, in import datasets File "/home/lsy/Meta-DETR-main/datasets/**init**.py", line 6, in from .dataset import build File "/home/lsy/Meta-DETR-main/datasets/dataset.py", line 10, in from util.misc import get_local_rank, get_local_size File "/home/lsy/Meta-DETR-main/util/misc.py", line 24, in from torchvision.ops.misc import _NewEmptyTensorOp ImportError: cannot import name '_NewEmptyTensorOp' from 'torchvision.ops.misc' (/home/lyk/anaconda3/envs/mdetr/lib/python3.8/site-packages/torchvision/ops/misc.py) I encountered the above issue during runtime. My versions of torch and torchvision are as follows. pytorch == 1.10.q+cu111 torchvision == 0.11.2+cu111 Could you please advise how to resolve this?

Hello, do you know how to train other datasets

**Comment by KarmaQI** [comment]
> 回溯（最近调用最后一次）：文件“main.py”，第 13 行，导入数据集文件“/home/lsy/Meta-DETR-main/datasets/**init**.py”，第 6 行，在 from .dataset 导入构建文件“/home/lsy/Meta-DETR-main/datasets/dataset.py”，第 10 行，在 from util.misc 导入get_local_rank，get_local_size文件“/home/lsy/Meta-DETR-main/util/misc.py”，第 24 行，在 from torchvision.ops.misc import _NewEmptyTensorOp ImportError：无法从“torchvision.ops.misc”（/home/lyk/anaconda3/envs/mdetr/lib/python3.8/site-packages/torchvision/ops/misc.py）导入名称“_NewEmptyTensorOp”我在运行时遇到了上述问题。我的 torch 和 torchvision 版本如下。 pytorch == 1.10.q+cu111 torchvision == 0.11.2+cu111 您能建议如何解决这个问题吗？

Hello, do you know how to train other datasets
